/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQuantStatsRouteImport } from './routes/_authenticated/quant-stats'
import { Route as AuthenticatedPsychologyRouteImport } from './routes/_authenticated/psychology'
import { Route as AuthenticatedProbabilityRouteImport } from './routes/_authenticated/probability'
import { Route as AuthenticatedMonteCarloRouteImport } from './routes/_authenticated/monte-carlo'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedEquityRouteImport } from './routes/_authenticated/equity'
import { Route as AuthenticatedDrawdownRouteImport } from './routes/_authenticated/drawdown'
import { Route as AuthenticatedDistributionRouteImport } from './routes/_authenticated/distribution'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCorrelationsRouteImport } from './routes/_authenticated/correlations'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuantStatsRoute = AuthenticatedQuantStatsRouteImport.update({
  id: '/quant-stats',
  path: '/quant-stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPsychologyRoute = AuthenticatedPsychologyRouteImport.update({
  id: '/psychology',
  path: '/psychology',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProbabilityRoute =
  AuthenticatedProbabilityRouteImport.update({
    id: '/probability',
    path: '/probability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonteCarloRoute = AuthenticatedMonteCarloRouteImport.update({
  id: '/monte-carlo',
  path: '/monte-carlo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquityRoute = AuthenticatedEquityRouteImport.update({
  id: '/equity',
  path: '/equity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDrawdownRoute = AuthenticatedDrawdownRouteImport.update({
  id: '/drawdown',
  path: '/drawdown',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDistributionRoute =
  AuthenticatedDistributionRouteImport.update({
    id: '/distribution',
    path: '/distribution',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCorrelationsRoute =
  AuthenticatedCorrelationsRouteImport.update({
    id: '/correlations',
    path: '/correlations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/correlations': typeof AuthenticatedCorrelationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distribution': typeof AuthenticatedDistributionRoute
  '/drawdown': typeof AuthenticatedDrawdownRoute
  '/equity': typeof AuthenticatedEquityRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/monte-carlo': typeof AuthenticatedMonteCarloRoute
  '/probability': typeof AuthenticatedProbabilityRoute
  '/psychology': typeof AuthenticatedPsychologyRoute
  '/quant-stats': typeof AuthenticatedQuantStatsRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/correlations': typeof AuthenticatedCorrelationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distribution': typeof AuthenticatedDistributionRoute
  '/drawdown': typeof AuthenticatedDrawdownRoute
  '/equity': typeof AuthenticatedEquityRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/monte-carlo': typeof AuthenticatedMonteCarloRoute
  '/probability': typeof AuthenticatedProbabilityRoute
  '/psychology': typeof AuthenticatedPsychologyRoute
  '/quant-stats': typeof AuthenticatedQuantStatsRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/correlations': typeof AuthenticatedCorrelationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/distribution': typeof AuthenticatedDistributionRoute
  '/_authenticated/drawdown': typeof AuthenticatedDrawdownRoute
  '/_authenticated/equity': typeof AuthenticatedEquityRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/monte-carlo': typeof AuthenticatedMonteCarloRoute
  '/_authenticated/probability': typeof AuthenticatedProbabilityRoute
  '/_authenticated/psychology': typeof AuthenticatedPsychologyRoute
  '/_authenticated/quant-stats': typeof AuthenticatedQuantStatsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/coach'
    | '/correlations'
    | '/dashboard'
    | '/distribution'
    | '/drawdown'
    | '/equity'
    | '/journal'
    | '/monte-carlo'
    | '/probability'
    | '/psychology'
    | '/quant-stats'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/coach'
    | '/correlations'
    | '/dashboard'
    | '/distribution'
    | '/drawdown'
    | '/equity'
    | '/journal'
    | '/monte-carlo'
    | '/probability'
    | '/psychology'
    | '/quant-stats'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/coach'
    | '/_authenticated/correlations'
    | '/_authenticated/dashboard'
    | '/_authenticated/distribution'
    | '/_authenticated/drawdown'
    | '/_authenticated/equity'
    | '/_authenticated/journal'
    | '/_authenticated/monte-carlo'
    | '/_authenticated/probability'
    | '/_authenticated/psychology'
    | '/_authenticated/quant-stats'
    | '/_authenticated/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quant-stats': {
      id: '/_authenticated/quant-stats'
      path: '/quant-stats'
      fullPath: '/quant-stats'
      preLoaderRoute: typeof AuthenticatedQuantStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/psychology': {
      id: '/_authenticated/psychology'
      path: '/psychology'
      fullPath: '/psychology'
      preLoaderRoute: typeof AuthenticatedPsychologyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/probability': {
      id: '/_authenticated/probability'
      path: '/probability'
      fullPath: '/probability'
      preLoaderRoute: typeof AuthenticatedProbabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monte-carlo': {
      id: '/_authenticated/monte-carlo'
      path: '/monte-carlo'
      fullPath: '/monte-carlo'
      preLoaderRoute: typeof AuthenticatedMonteCarloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equity': {
      id: '/_authenticated/equity'
      path: '/equity'
      fullPath: '/equity'
      preLoaderRoute: typeof AuthenticatedEquityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drawdown': {
      id: '/_authenticated/drawdown'
      path: '/drawdown'
      fullPath: '/drawdown'
      preLoaderRoute: typeof AuthenticatedDrawdownRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distribution': {
      id: '/_authenticated/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof AuthenticatedDistributionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/correlations': {
      id: '/_authenticated/correlations'
      path: '/correlations'
      fullPath: '/correlations'
      preLoaderRoute: typeof AuthenticatedCorrelationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedCorrelationsRoute: typeof AuthenticatedCorrelationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDistributionRoute: typeof AuthenticatedDistributionRoute
  AuthenticatedDrawdownRoute: typeof AuthenticatedDrawdownRoute
  AuthenticatedEquityRoute: typeof AuthenticatedEquityRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedMonteCarloRoute: typeof AuthenticatedMonteCarloRoute
  AuthenticatedProbabilityRoute: typeof AuthenticatedProbabilityRoute
  AuthenticatedPsychologyRoute: typeof AuthenticatedPsychologyRoute
  AuthenticatedQuantStatsRoute: typeof AuthenticatedQuantStatsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedCorrelationsRoute: AuthenticatedCorrelationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDistributionRoute: AuthenticatedDistributionRoute,
  AuthenticatedDrawdownRoute: AuthenticatedDrawdownRoute,
  AuthenticatedEquityRoute: AuthenticatedEquityRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedMonteCarloRoute: AuthenticatedMonteCarloRoute,
  AuthenticatedProbabilityRoute: AuthenticatedProbabilityRoute,
  AuthenticatedPsychologyRoute: AuthenticatedPsychologyRoute,
  AuthenticatedQuantStatsRoute: AuthenticatedQuantStatsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
