/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTradeReplayRouteImport } from './routes/_authenticated/trade-replay'
import { Route as AuthenticatedStrategyLabRouteImport } from './routes/_authenticated/strategy-lab'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSessionIntelligenceRouteImport } from './routes/_authenticated/session-intelligence'
import { Route as AuthenticatedRiskOfRuinRouteImport } from './routes/_authenticated/risk-of-ruin'
import { Route as AuthenticatedQuantStatsRouteImport } from './routes/_authenticated/quant-stats'
import { Route as AuthenticatedPsychologyRouteImport } from './routes/_authenticated/psychology'
import { Route as AuthenticatedProbabilityRouteImport } from './routes/_authenticated/probability'
import { Route as AuthenticatedPositionSizingRouteImport } from './routes/_authenticated/position-sizing'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedPerformanceMetricsRouteImport } from './routes/_authenticated/performance-metrics'
import { Route as AuthenticatedMonteCarloRouteImport } from './routes/_authenticated/monte-carlo'
import { Route as AuthenticatedMarketIntelligenceRouteImport } from './routes/_authenticated/market-intelligence'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedEquityRouteImport } from './routes/_authenticated/equity'
import { Route as AuthenticatedDrawdownRouteImport } from './routes/_authenticated/drawdown'
import { Route as AuthenticatedDistributionRouteImport } from './routes/_authenticated/distribution'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCsvImportRouteImport } from './routes/_authenticated/csv-import'
import { Route as AuthenticatedCorrelationsRouteImport } from './routes/_authenticated/correlations'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedBenchmarkRouteImport } from './routes/_authenticated/benchmark'
import { Route as AuthenticatedBehaviorRouteImport } from './routes/_authenticated/behavior'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTradeReplayRoute =
  AuthenticatedTradeReplayRouteImport.update({
    id: '/trade-replay',
    path: '/trade-replay',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStrategyLabRoute =
  AuthenticatedStrategyLabRouteImport.update({
    id: '/strategy-lab',
    path: '/strategy-lab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionIntelligenceRoute =
  AuthenticatedSessionIntelligenceRouteImport.update({
    id: '/session-intelligence',
    path: '/session-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRiskOfRuinRoute = AuthenticatedRiskOfRuinRouteImport.update({
  id: '/risk-of-ruin',
  path: '/risk-of-ruin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuantStatsRoute = AuthenticatedQuantStatsRouteImport.update({
  id: '/quant-stats',
  path: '/quant-stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPsychologyRoute = AuthenticatedPsychologyRouteImport.update({
  id: '/psychology',
  path: '/psychology',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProbabilityRoute =
  AuthenticatedProbabilityRouteImport.update({
    id: '/probability',
    path: '/probability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPositionSizingRoute =
  AuthenticatedPositionSizingRouteImport.update({
    id: '/position-sizing',
    path: '/position-sizing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceMetricsRoute =
  AuthenticatedPerformanceMetricsRouteImport.update({
    id: '/performance-metrics',
    path: '/performance-metrics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonteCarloRoute = AuthenticatedMonteCarloRouteImport.update({
  id: '/monte-carlo',
  path: '/monte-carlo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketIntelligenceRoute =
  AuthenticatedMarketIntelligenceRouteImport.update({
    id: '/market-intelligence',
    path: '/market-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquityRoute = AuthenticatedEquityRouteImport.update({
  id: '/equity',
  path: '/equity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDrawdownRoute = AuthenticatedDrawdownRouteImport.update({
  id: '/drawdown',
  path: '/drawdown',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDistributionRoute =
  AuthenticatedDistributionRouteImport.update({
    id: '/distribution',
    path: '/distribution',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCsvImportRoute = AuthenticatedCsvImportRouteImport.update({
  id: '/csv-import',
  path: '/csv-import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCorrelationsRoute =
  AuthenticatedCorrelationsRouteImport.update({
    id: '/correlations',
    path: '/correlations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBenchmarkRoute = AuthenticatedBenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBehaviorRoute = AuthenticatedBehaviorRouteImport.update({
  id: '/behavior',
  path: '/behavior',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/behavior': typeof AuthenticatedBehaviorRoute
  '/benchmark': typeof AuthenticatedBenchmarkRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/correlations': typeof AuthenticatedCorrelationsRoute
  '/csv-import': typeof AuthenticatedCsvImportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distribution': typeof AuthenticatedDistributionRoute
  '/drawdown': typeof AuthenticatedDrawdownRoute
  '/equity': typeof AuthenticatedEquityRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/market-intelligence': typeof AuthenticatedMarketIntelligenceRoute
  '/monte-carlo': typeof AuthenticatedMonteCarloRoute
  '/performance-metrics': typeof AuthenticatedPerformanceMetricsRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/position-sizing': typeof AuthenticatedPositionSizingRoute
  '/probability': typeof AuthenticatedProbabilityRoute
  '/psychology': typeof AuthenticatedPsychologyRoute
  '/quant-stats': typeof AuthenticatedQuantStatsRoute
  '/risk-of-ruin': typeof AuthenticatedRiskOfRuinRoute
  '/session-intelligence': typeof AuthenticatedSessionIntelligenceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategy-lab': typeof AuthenticatedStrategyLabRoute
  '/trade-replay': typeof AuthenticatedTradeReplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/behavior': typeof AuthenticatedBehaviorRoute
  '/benchmark': typeof AuthenticatedBenchmarkRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/correlations': typeof AuthenticatedCorrelationsRoute
  '/csv-import': typeof AuthenticatedCsvImportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distribution': typeof AuthenticatedDistributionRoute
  '/drawdown': typeof AuthenticatedDrawdownRoute
  '/equity': typeof AuthenticatedEquityRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/market-intelligence': typeof AuthenticatedMarketIntelligenceRoute
  '/monte-carlo': typeof AuthenticatedMonteCarloRoute
  '/performance-metrics': typeof AuthenticatedPerformanceMetricsRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/position-sizing': typeof AuthenticatedPositionSizingRoute
  '/probability': typeof AuthenticatedProbabilityRoute
  '/psychology': typeof AuthenticatedPsychologyRoute
  '/quant-stats': typeof AuthenticatedQuantStatsRoute
  '/risk-of-ruin': typeof AuthenticatedRiskOfRuinRoute
  '/session-intelligence': typeof AuthenticatedSessionIntelligenceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategy-lab': typeof AuthenticatedStrategyLabRoute
  '/trade-replay': typeof AuthenticatedTradeReplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/behavior': typeof AuthenticatedBehaviorRoute
  '/_authenticated/benchmark': typeof AuthenticatedBenchmarkRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/correlations': typeof AuthenticatedCorrelationsRoute
  '/_authenticated/csv-import': typeof AuthenticatedCsvImportRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/distribution': typeof AuthenticatedDistributionRoute
  '/_authenticated/drawdown': typeof AuthenticatedDrawdownRoute
  '/_authenticated/equity': typeof AuthenticatedEquityRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/market-intelligence': typeof AuthenticatedMarketIntelligenceRoute
  '/_authenticated/monte-carlo': typeof AuthenticatedMonteCarloRoute
  '/_authenticated/performance-metrics': typeof AuthenticatedPerformanceMetricsRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/position-sizing': typeof AuthenticatedPositionSizingRoute
  '/_authenticated/probability': typeof AuthenticatedProbabilityRoute
  '/_authenticated/psychology': typeof AuthenticatedPsychologyRoute
  '/_authenticated/quant-stats': typeof AuthenticatedQuantStatsRoute
  '/_authenticated/risk-of-ruin': typeof AuthenticatedRiskOfRuinRoute
  '/_authenticated/session-intelligence': typeof AuthenticatedSessionIntelligenceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/strategy-lab': typeof AuthenticatedStrategyLabRoute
  '/_authenticated/trade-replay': typeof AuthenticatedTradeReplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/behavior'
    | '/benchmark'
    | '/coach'
    | '/correlations'
    | '/csv-import'
    | '/dashboard'
    | '/distribution'
    | '/drawdown'
    | '/equity'
    | '/journal'
    | '/market-intelligence'
    | '/monte-carlo'
    | '/performance-metrics'
    | '/portfolio'
    | '/position-sizing'
    | '/probability'
    | '/psychology'
    | '/quant-stats'
    | '/risk-of-ruin'
    | '/session-intelligence'
    | '/settings'
    | '/strategy-lab'
    | '/trade-replay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/behavior'
    | '/benchmark'
    | '/coach'
    | '/correlations'
    | '/csv-import'
    | '/dashboard'
    | '/distribution'
    | '/drawdown'
    | '/equity'
    | '/journal'
    | '/market-intelligence'
    | '/monte-carlo'
    | '/performance-metrics'
    | '/portfolio'
    | '/position-sizing'
    | '/probability'
    | '/psychology'
    | '/quant-stats'
    | '/risk-of-ruin'
    | '/session-intelligence'
    | '/settings'
    | '/strategy-lab'
    | '/trade-replay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/behavior'
    | '/_authenticated/benchmark'
    | '/_authenticated/coach'
    | '/_authenticated/correlations'
    | '/_authenticated/csv-import'
    | '/_authenticated/dashboard'
    | '/_authenticated/distribution'
    | '/_authenticated/drawdown'
    | '/_authenticated/equity'
    | '/_authenticated/journal'
    | '/_authenticated/market-intelligence'
    | '/_authenticated/monte-carlo'
    | '/_authenticated/performance-metrics'
    | '/_authenticated/portfolio'
    | '/_authenticated/position-sizing'
    | '/_authenticated/probability'
    | '/_authenticated/psychology'
    | '/_authenticated/quant-stats'
    | '/_authenticated/risk-of-ruin'
    | '/_authenticated/session-intelligence'
    | '/_authenticated/settings'
    | '/_authenticated/strategy-lab'
    | '/_authenticated/trade-replay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trade-replay': {
      id: '/_authenticated/trade-replay'
      path: '/trade-replay'
      fullPath: '/trade-replay'
      preLoaderRoute: typeof AuthenticatedTradeReplayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategy-lab': {
      id: '/_authenticated/strategy-lab'
      path: '/strategy-lab'
      fullPath: '/strategy-lab'
      preLoaderRoute: typeof AuthenticatedStrategyLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session-intelligence': {
      id: '/_authenticated/session-intelligence'
      path: '/session-intelligence'
      fullPath: '/session-intelligence'
      preLoaderRoute: typeof AuthenticatedSessionIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risk-of-ruin': {
      id: '/_authenticated/risk-of-ruin'
      path: '/risk-of-ruin'
      fullPath: '/risk-of-ruin'
      preLoaderRoute: typeof AuthenticatedRiskOfRuinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quant-stats': {
      id: '/_authenticated/quant-stats'
      path: '/quant-stats'
      fullPath: '/quant-stats'
      preLoaderRoute: typeof AuthenticatedQuantStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/psychology': {
      id: '/_authenticated/psychology'
      path: '/psychology'
      fullPath: '/psychology'
      preLoaderRoute: typeof AuthenticatedPsychologyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/probability': {
      id: '/_authenticated/probability'
      path: '/probability'
      fullPath: '/probability'
      preLoaderRoute: typeof AuthenticatedProbabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/position-sizing': {
      id: '/_authenticated/position-sizing'
      path: '/position-sizing'
      fullPath: '/position-sizing'
      preLoaderRoute: typeof AuthenticatedPositionSizingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance-metrics': {
      id: '/_authenticated/performance-metrics'
      path: '/performance-metrics'
      fullPath: '/performance-metrics'
      preLoaderRoute: typeof AuthenticatedPerformanceMetricsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monte-carlo': {
      id: '/_authenticated/monte-carlo'
      path: '/monte-carlo'
      fullPath: '/monte-carlo'
      preLoaderRoute: typeof AuthenticatedMonteCarloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market-intelligence': {
      id: '/_authenticated/market-intelligence'
      path: '/market-intelligence'
      fullPath: '/market-intelligence'
      preLoaderRoute: typeof AuthenticatedMarketIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equity': {
      id: '/_authenticated/equity'
      path: '/equity'
      fullPath: '/equity'
      preLoaderRoute: typeof AuthenticatedEquityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drawdown': {
      id: '/_authenticated/drawdown'
      path: '/drawdown'
      fullPath: '/drawdown'
      preLoaderRoute: typeof AuthenticatedDrawdownRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distribution': {
      id: '/_authenticated/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof AuthenticatedDistributionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/csv-import': {
      id: '/_authenticated/csv-import'
      path: '/csv-import'
      fullPath: '/csv-import'
      preLoaderRoute: typeof AuthenticatedCsvImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/correlations': {
      id: '/_authenticated/correlations'
      path: '/correlations'
      fullPath: '/correlations'
      preLoaderRoute: typeof AuthenticatedCorrelationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/benchmark': {
      id: '/_authenticated/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof AuthenticatedBenchmarkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/behavior': {
      id: '/_authenticated/behavior'
      path: '/behavior'
      fullPath: '/behavior'
      preLoaderRoute: typeof AuthenticatedBehaviorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBehaviorRoute: typeof AuthenticatedBehaviorRoute
  AuthenticatedBenchmarkRoute: typeof AuthenticatedBenchmarkRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedCorrelationsRoute: typeof AuthenticatedCorrelationsRoute
  AuthenticatedCsvImportRoute: typeof AuthenticatedCsvImportRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDistributionRoute: typeof AuthenticatedDistributionRoute
  AuthenticatedDrawdownRoute: typeof AuthenticatedDrawdownRoute
  AuthenticatedEquityRoute: typeof AuthenticatedEquityRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedMarketIntelligenceRoute: typeof AuthenticatedMarketIntelligenceRoute
  AuthenticatedMonteCarloRoute: typeof AuthenticatedMonteCarloRoute
  AuthenticatedPerformanceMetricsRoute: typeof AuthenticatedPerformanceMetricsRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedPositionSizingRoute: typeof AuthenticatedPositionSizingRoute
  AuthenticatedProbabilityRoute: typeof AuthenticatedProbabilityRoute
  AuthenticatedPsychologyRoute: typeof AuthenticatedPsychologyRoute
  AuthenticatedQuantStatsRoute: typeof AuthenticatedQuantStatsRoute
  AuthenticatedRiskOfRuinRoute: typeof AuthenticatedRiskOfRuinRoute
  AuthenticatedSessionIntelligenceRoute: typeof AuthenticatedSessionIntelligenceRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStrategyLabRoute: typeof AuthenticatedStrategyLabRoute
  AuthenticatedTradeReplayRoute: typeof AuthenticatedTradeReplayRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBehaviorRoute: AuthenticatedBehaviorRoute,
  AuthenticatedBenchmarkRoute: AuthenticatedBenchmarkRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedCorrelationsRoute: AuthenticatedCorrelationsRoute,
  AuthenticatedCsvImportRoute: AuthenticatedCsvImportRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDistributionRoute: AuthenticatedDistributionRoute,
  AuthenticatedDrawdownRoute: AuthenticatedDrawdownRoute,
  AuthenticatedEquityRoute: AuthenticatedEquityRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedMarketIntelligenceRoute: AuthenticatedMarketIntelligenceRoute,
  AuthenticatedMonteCarloRoute: AuthenticatedMonteCarloRoute,
  AuthenticatedPerformanceMetricsRoute: AuthenticatedPerformanceMetricsRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedPositionSizingRoute: AuthenticatedPositionSizingRoute,
  AuthenticatedProbabilityRoute: AuthenticatedProbabilityRoute,
  AuthenticatedPsychologyRoute: AuthenticatedPsychologyRoute,
  AuthenticatedQuantStatsRoute: AuthenticatedQuantStatsRoute,
  AuthenticatedRiskOfRuinRoute: AuthenticatedRiskOfRuinRoute,
  AuthenticatedSessionIntelligenceRoute: AuthenticatedSessionIntelligenceRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStrategyLabRoute: AuthenticatedStrategyLabRoute,
  AuthenticatedTradeReplayRoute: AuthenticatedTradeReplayRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
